import { useMemo, useState, type CSSProperties } from 'react'
import { ArrowDownRight, ArrowUpRight, ChevronDown, ChevronRight, Circle, Menu, Play, Sparkles, Wallet, X } from 'lucide-react'

type Universe = { id: string; title: string; artist: string; palette: string; rarity: string; year: string; edition: string; lore: string; owned?: boolean; accent: string }

const universes: Universe[] = [
  { id: '001', title: 'The First Light', artist: 'Ari Vale', palette: 'violet', rarity: 'Common', year: '2026', edition: '1 / 150', lore: 'Before the signal, there was a single warm frequency. This is where the OC first learned to listen.', owned: true, accent: '#c98bff' },
  { id: '002', title: 'Salt Cathedral', artist: 'Mina Osei', palette: 'sand', rarity: 'Rare', year: '2026', edition: '1 / 80', lore: 'A sunken archive where every memory is preserved in salt. The tide remembers what the OC forgets.', accent: '#ecd06f' },
  { id: '003', title: 'Blue Hour', artist: 'Kaito Ren', palette: 'blue', rarity: 'Common', year: '2026', edition: '1 / 120', lore: 'The city only exists between two seconds. Arrive early, or stay forever.', accent: '#298dff' },
  { id: '004', title: 'The Orchard', artist: 'Noa Saint', palette: 'rose', rarity: 'Secret', year: '2026', edition: '1 / 30', lore: 'A hidden branch of the canon. Its fruit is a map to every self the OC has not become.', accent: '#ff8fbd' },
]

const products = [
  { name: 'Signal / Long Sleeve', type: 'Holder edition', price: '0.04 ETH', access: 'Holder early access', art: 'product-blue' },
  { name: 'Universe 002 / Print', type: 'Edition of 50', price: '$140', access: 'Open edition', art: 'product-gold' },
  { name: 'The Archive / Zine', type: 'Lore object', price: '$48', access: 'Available now', art: 'product-paper' },
]

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [view, setView] = useState<'room' | 'grid'>('room')
  const [filter, setFilter] = useState('All')
  const [selected, setSelected] = useState<Universe | null>(null)
  const [wallet, setWallet] = useState<'idle' | 'connecting' | 'verified'>('idle')
  const [reveal, setReveal] = useState(false)
  const [chatOpen, setChatOpen] = useState(false)
  const [message, setMessage] = useState('')
  const [chatMessages, setChatMessages] = useState<string[]>([])
  const [specOpen, setSpecOpen] = useState<string | null>(null)

  const filtered = useMemo(() => filter === 'All' ? universes : universes.filter(u => u.rarity === filter), [filter])
  const connectWallet = () => { setWallet('connecting'); window.setTimeout(() => setWallet('verified'), 850) }
  const sendMessage = () => { if (!message.trim()) return; setChatMessages(prev => [...prev, message.trim()]); setMessage('') }

  return <div className="app-shell">
    <div className="grain" aria-hidden="true" />
    <header className="topbar">
      <a className="brand" href="#top" aria-label="OC Universe home"><span className="brand-mark"><i /><i /><i /></span><span>OC / UNIVERSE</span></a>
      <nav className={menuOpen ? 'nav-links open' : 'nav-links'}>
        <a href="#multiverse" onClick={() => setMenuOpen(false)}>Multiverse <span>01</span></a>
        <a href="#perks" onClick={() => setMenuOpen(false)}>Holder access <span>02</span></a>
        <a href="#persona" onClick={() => setMenuOpen(false)}>Persona <span>03</span></a>
      </nav>
      <div className="top-actions"><span className="network-status"><Circle size={7} fill="currentColor" /> Base / live</span><button className={wallet === 'verified' ? 'wallet-button verified' : 'wallet-button'} onClick={connectWallet}><Wallet size={14} /> {wallet === 'verified' ? '0x7F...91C2' : wallet === 'connecting' ? 'Verifying...' : 'Connect wallet'}</button></div>
      <button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen ? <X /> : <Menu />}</button>
    </header>

    <main id="top">
      <section className="hero section-pad">
        <div className="hero-orbit orbit-a" /><div className="hero-orbit orbit-b" /><div className="hero-sigil"><span>OC</span><small>∞</small></div>
        <div className="hero-copy reveal"><p className="eyebrow"><span className="eyebrow-line" /> A living canon / 2026</p><h1>One character.<br /><em>Infinite selves.</em></h1><p className="hero-deck">The Multiverse is an evolving collection of official alternate realities — each one commissioned, numbered, and made to be found.</p><div className="hero-ctas"><a className="button button-primary" href="#multiverse">Enter the Multiverse <ArrowDownRight size={16} /></a><a className="text-link" href="#lore">Read the origin <ChevronRight size={15} /></a></div></div>
        <div className="hero-meta"><span>01 / 04</span><span className="meta-rule" /><span>Scroll to explore</span><span className="scroll-dot" /></div>
        <div className="hero-caption"><span>Signal received</span><strong>UNIVERSE #001</strong><small>THE FIRST LIGHT — ARI VALE</small></div>
      </section>

      <section id="lore" className="lore section-pad">
        <div className="section-kicker"><span>00 — Origin</span><span>The character behind the canon</span></div>
        <div className="lore-grid"><div className="lore-title"><p className="eyebrow">A note from the archive</p><h2>There is no<br /><em>original.</em></h2></div><div className="lore-copy"><p className="lead">The OC was never meant to stay in one place. Every artist sees a different door in the same face — a different weather system, a different way home.</p><p>What began as a profile picture became a language for alternate selves. The Multiverse gives those selves a permanent address: numbered, credited, and open to anyone who wants to look closer.</p><a className="text-link" href="#multiverse">Follow the signal <ArrowDownRight size={15} /></a></div></div>
        <div className="lore-strip"><span>CANON / 04 UNIVERSES</span><span>ARTISTS / 04 VOICES</span><span>RELEASE / EVERY FEW WEEKS</span><span>CHAIN / BASE</span></div>
      </section>

      <section id="multiverse" className="multiverse section-pad">
        <div className="section-heading"><div><p className="eyebrow">01 — The anchor</p><h2>The <em>Multiverse</em></h2></div><p className="section-intro">A growing archive of official reinterpretations. Enter the room, find a universe, stay for the lore.</p></div>
        <div className="gallery-toolbar"><div className="view-toggle"><button className={view === 'room' ? 'active' : ''} onClick={() => setView('room')}>Spatial room</button><button className={view === 'grid' ? 'active' : ''} onClick={() => setView('grid')}>Catalog grid</button></div><div className="filter-group">{['All','Common','Rare','Secret'].map(item => <button key={item} className={filter === item ? 'filter active' : 'filter'} onClick={() => setFilter(item)}>{item}</button>)}</div></div>
        {view === 'room' ? <div className="room-view"><div className="room-copy"><span className="room-index">ROOM / 001</span><h3>Walk between<br /><em>the versions.</em></h3><p>Drag your attention across the room. Each light is a different universe — a fragment of the canon waiting to resolve.</p><button className="button button-ghost" onClick={() => setView('grid')}>Open the catalog <ArrowUpRight size={15} /></button></div><div className="room-art"><div className="room-sphere" /><div className="room-frame frame-one" /><div className="room-frame frame-two" /><div className="room-label label-one">#001 / ARI VALE</div><div className="room-label label-two">#004 / SECRET</div><div className="room-star star-one" /><div className="room-star star-two" /></div></div> : <div className="catalog-grid">{filtered.map((u, i) => <button className={`universe-card card-${u.palette}`} key={u.id} onClick={() => setSelected(u)} style={{'--delay': `${i * 80}ms`, '--accent': u.accent} as CSSProperties}><div className="card-art"><div className="art-glow" /><div className="art-orb" /><span className="card-number">#{u.id}</span><span className="card-state">{u.rarity}</span>{u.owned && <span className="owned-mark">Owned</span>}</div><div className="card-info"><div><span className="technical">{u.artist} / {u.year}</span><h3>{u.title}</h3></div><ArrowUpRight size={17} /></div><div className="card-foot"><span>{u.edition}</span><span>Explore story <ChevronRight size={12} /></span></div></button>)}</div>}
        <div className="gallery-footer"><span>Showing {filtered.length.toString().padStart(2, '0')} / 04 universes</span><span>New universe incoming <strong>14 : 06 : 22</strong></span></div>
      </section>

      <section id="perks" className="access-section section-pad"><div className="access-glow" /><div className="section-kicker"><span>02 — Holder access</span><span>Reserved for the early believers</span></div><div className="access-layout"><div><p className="eyebrow blue-text">Your key to the next room</p><h2>Hold the original.<br /><em>Unlock what comes next.</em></h2><p className="section-intro">Connect your wallet to see which universes are already yours — and unlock first access to the next one.</p><button className="button button-primary blue-button" onClick={connectWallet}><Wallet size={15} /> {wallet === 'verified' ? 'Holder verified' : wallet === 'connecting' ? 'Checking the chain...' : 'Verify holder status'}</button></div><div className={wallet === 'verified' ? 'wallet-panel is-verified' : 'wallet-panel'}><div className="panel-top"><span className="technical">WALLET / STATUS</span><span className="status-badge"><Circle size={7} fill="currentColor" /> {wallet === 'verified' ? 'Verified holder' : 'Awaiting connection'}</span></div>{wallet === 'verified' ? <><div className="wallet-address">0x7F4A...91C2 <span>● TIER 02</span></div><div className="wallet-stats"><div><strong>02</strong><span>universes owned</span></div><div><strong>15%</strong><span>holder discount</span></div><div><strong>48h</strong><span>early access</span></div></div><div className="owned-row"><span className="mini-art mini-violet">#001</span><span className="mini-art mini-blue">#003</span><span className="owned-caption">Your collection is growing.<br /><small>Next unlock: Universe #005</small></span></div></> : <div className="wallet-empty"><Wallet size={22} /><p>Connect to reveal your access tier, owned universes, and personalized drop window.</p><span className="technical">NO WALLET CONNECTED</span></div>}</div></div><div className="perk-row"><span>Holder perks</span><span>01 / Early claim</span><span>02 / Exclusive SKUs</span><span>03 / Auto-applied discount</span><span>04 / Free shipping</span></div></section>

      <section id="store" className="store section-pad"><div className="section-heading"><div><p className="eyebrow">03 — The store</p><h2>Objects from<br /><em>the signal.</em></h2></div><p className="section-intro">Physical pieces, digital editions, and the stories that connect them. Every purchase returns a fragment of the Multiverse to you.</p></div><div className="store-layout"><div className="product-column">{products.map((p, i) => <div className="product-row" key={p.name}><div className={`product-art ${p.art}`}><span>OC / {String(i + 1).padStart(2,'0')}</span><div className="product-shape" /></div><div className="product-details"><span className="technical">{p.type}</span><h3>{p.name}</h3><div className="product-bottom"><span>{p.price}</span><button onClick={() => setSelected(universes[i])}>{p.access} <ArrowUpRight size={13} /></button></div></div></div>)}</div><div className="drop-feed"><div className="feed-head"><span className="technical">LIVE DROP FEED</span><span className="live-dot"><i /> updating</span></div><article><span className="technical">02 MIN AGO / PERSONA</span><h3>“The next door is painted the color of a storm you haven't seen yet.”</h3><a href="#persona">Read the transmission <ArrowUpRight size={13} /></a></article><article><span className="technical">TODAY / HOLDER DROP</span><h3>Universe #002 / Salt Cathedral is now available to verified holders.</h3><a href="#perks">Check your access <ArrowUpRight size={13} /></a></article></div></div></section>

      <section id="collectibles" className="collectibles section-pad"><div className="collectible-copy"><p className="eyebrow gold-text">04 — Proof of purchase</p><h2>Every purchase<br />pulls a <em>story.</em></h2><p className="section-intro">A random, numbered fragment from the live Multiverse — minted after checkout. Complete the set to unlock the rarest room.</p><button className="button button-gold" onClick={() => setReveal(true)}><Sparkles size={15} /> Preview a pull</button></div><div className="collector-card"><div className="collector-top"><span className="technical">COLLECTOR / PROGRESS</span><span>02 / 04</span></div><div className="stamp-grid">{universes.map((u, i) => <div className={i < 2 ? 'stamp filled' : 'stamp'} key={u.id}><span>{u.id}</span><small>{i < 2 ? u.artist : 'LOCKED'}</small></div>)}</div><div className="progress-label"><span>Set completion</span><strong>50%</strong></div><div className="progress"><i /></div><div className="milestone"><div className="milestone-icon">✦</div><div><span className="technical">MILESTONE 03</span><p>Next purchase guarantees a rare pull.</p></div><ChevronRight size={17} /></div></div></section>

      <section id="persona" className="persona section-pad"><div className="persona-canvas"><div className="persona-grid" /><div className="persona-core"><div className="core-ring ring-one" /><div className="core-ring ring-two" /><div className="core-eye" /></div><span className="persona-coordinate coord-a">43.117 / -72.004</span><span className="persona-coordinate coord-b">VOICE / ACTIVE</span></div><div className="persona-copy"><p className="eyebrow blue-text">05 — The AI persona</p><h2>Ask the OC<br /><em>what comes next.</em></h2><p className="section-intro">A voice that remembers every universe, teases the next drop, and stays awake when you are not.</p><div className="persona-actions"><button className="button button-primary" onClick={() => setChatOpen(true)}><Play size={14} fill="currentColor" /> Open the conversation</button><span className="technical">PUBLIC / NO MEMORY / IN CHARACTER</span></div></div><div className="persona-ticker"><span>THE SIGNAL IS NEVER SILENT</span><span>THE SIGNAL IS NEVER SILENT</span><span>THE SIGNAL IS NEVER SILENT</span></div></section>

      <section id="specs" className="specs section-pad"><div className="section-kicker"><span>06 — The fine print</span><span>Trust, made legible</span></div><div className="specs-layout"><div><h2>Built to keep<br /><em>growing.</em></h2><p className="section-intro">The Multiverse funds its own expansion. Every drop is transparent, every artist stays credited, every new room becomes part of the map.</p></div><div className="spec-list">{[['01','Revenue split','50% artist / 50% studio'],['02','Edition logic','50 — 200 per universe'],['03','Minting layer','Base / low-fee / IPFS metadata'],['04','Persona guardrails','No memory / no auto-posting']].map(([n,t,d]) => <button className={specOpen === n ? 'spec-row open' : 'spec-row'} key={n} onClick={() => setSpecOpen(specOpen === n ? null : n)}><span className="spec-number">{n}</span><span><strong>{t}</strong>{specOpen === n && <small>{d}</small>}</span><ChevronDown size={16} /></button>)}</div></div></section>
    </main>

    <footer className="footer"><div className="footer-brand"><span className="brand-mark"><i /><i /><i /></span><strong>OC / UNIVERSE</strong><p>A living canon of alternate selves.</p></div><div className="footer-links"><a href="#multiverse">Multiverse</a><a href="#perks">Holder access</a><a href="#store">Store</a><a href="#persona">Persona</a></div><div className="footer-end"><span className="technical">© 2026 OC UNIVERSE</span><span className="technical">BUILT FOR THE CURIOUS</span></div></footer>

    {selected && <div className="modal-backdrop" onClick={() => setSelected(null)}><div className="universe-modal" onClick={e => e.stopPropagation()}><button className="close-button" onClick={() => setSelected(null)} aria-label="Close"><X size={18} /></button><div className={`modal-art card-${selected.palette}`} style={{'--accent': selected.accent} as CSSProperties}><div className="art-glow" /><div className="art-orb" /><span className="card-number">#{selected.id}</span><span className="card-state">{selected.rarity}</span></div><div className="modal-body"><span className="technical">{selected.artist} / {selected.year} / {selected.edition}</span><h2>{selected.title}</h2><p>{selected.lore}</p><div className="modal-meta"><div><span className="technical">ACCESS</span><strong>{selected.owned ? 'In your collection' : 'Public in 14 : 06 : 22'}</strong></div><div><span className="technical">ROYALTY</span><strong>50 / 50 split</strong></div></div><button className="button button-primary" onClick={() => { setSelected(null); document.querySelector('#perks')?.scrollIntoView({behavior:'smooth'}) }}>{selected.owned ? 'View collection' : 'Check holder access'} <ArrowUpRight size={15} /></button></div></div></div>}
    {reveal && <div className="modal-backdrop" onClick={() => setReveal(false)}><div className="reveal-modal" onClick={e => e.stopPropagation()}><button className="close-button" onClick={() => setReveal(false)} aria-label="Close"><X size={18} /></button><span className="technical gold-text">PULL / RANDOMIZED / #014</span><div className="reveal-card"><div className="reveal-card-back"><span>OC</span><small>THE MULTIVERSE</small></div><div className="reveal-light" /></div><h2>Your next fragment<br /><em>is waiting.</em></h2><p>This preview reveals the shape of a future collectible. Every real purchase mints a limited pull from the live catalog.</p><button className="button button-gold" onClick={() => setReveal(false)}>Return to the store</button></div></div>}
    {chatOpen && <div className="chat-panel"><div className="chat-head"><div><span className="technical blue-text">OC / PERSONA</span><strong>The signal is live.</strong></div><button onClick={() => setChatOpen(false)} aria-label="Close chat"><X size={18} /></button></div><div className="chat-body"><div className="chat-message persona-message">I know why you came. You want to know what comes after Universe #004. Ask me a better question.</div>{chatMessages.map((m, i) => <div className="chat-message user-message" key={i}>{m}</div>)}{chatMessages.length > 0 && <div className="chat-message persona-message">The answer is moving. Check back when the next room opens.</div>}</div><div className="chat-input"><input value={message} onChange={e => setMessage(e.target.value)} onKeyDown={e => e.key === 'Enter' && sendMessage()} placeholder="Ask about a universe..." /><button onClick={sendMessage} aria-label="Send"><ArrowUpRight size={16} /></button></div><div className="chat-foot technical">PUBLIC CHAT / DEMO RESPONSE / NO MEMORY</div></div>}
  </div>
}

export default App
